_target_: src.models.controlnet_module.ControlLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-5

# scheduler:
#   _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#   _partial_: true
#   mode: min
#   factor: 0.1
#   patience: 10

lr_scheduler: constant

unet: checkpoints
vae: checkpoints
text_encoder: checkpoints
froze_components: ["vae","text_encoder","unet"]
controlnet: null
diffusion_schedule: checkpoints
# compile model for faster training with pytorch 2.0
compile: false
