_target_: src.models.sdxl_t2i_module.StableDiffusionXLT2ILitModule

pretrained_model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0
revision: null
variant: null
pretrained_vae_model_name_or_path: null
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-5

lr_scheduler: constant
lr_warmup_steps: 500
lr_num_cycles: 1
lr_power: 1.0
max_train_steps: 100000
compile: false
