defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "{epoch:03d}-{val_loss:.2f}"
  monitor: "val/loss"
  mode: "min"
  save_last: True
  save_top_k: 10
  auto_insert_metric_name: True

early_stopping:
  monitor: "val/loss"
  patience: 100
  mode: "min"

model_summary:
  max_depth: -1
